### ISSUE TITLE
设置`ttimeoutlen`参数值时,能否做下兼容?

### ISSUE THREAD

**Issue by l-qing** [CodeFalling/fcitx-vim-osx#12]
感谢你维护了这个插件!
该插件在MacOS下,确实很方便,不会报错.
<hr>

我有个小建议,这里设置`ttimeoutlen`(等待键码或者映射的键序列完成的时间 单位ms)时,能否做下兼容处理?

目前是直接设置为了固定值50.
https://github.com/xcodebuild/fcitx-vim-osx/blob/f1dcc71b840f72b581ed38dbbd3df19fa783aa12/plugin/fcitx-osx.vim#L13

我的场景下需要调小该值,在我的`.vimrc`中配置了更小的值,但是加载本插件时,还是被修改为了50.
能否做下兼容处理,比如这样:
```
if &ttimeoutlen <= 0 || &ttimeoutlen > 50
    set ttimeoutlen=50
endif
```
我试了,在该值设为20时,该插件的功能还是正常的.

如果你愿意这么处理,但不想花时间,我也乐意提交PR.
谢谢你!

**Comment by xcodebuild** [comment]
来个 PR 吧 😆

**Comment by l-qing** [comment]
> 来个 PR 吧 😆

已提交,麻烦在有时间的时候,审核一下.谢谢!
<hr>

题外话:
我发现,使用了该插件后,从插入模式按`<Esc>`退出到普通模式时,很大概率会出现字符残影.
残影就是在原来插入模式下光标的地方,出现`^[`字样.
使用按键序列`a<Esc><Esc><Esc>`比较容易复现.
使用`j/k`移动光标后,残影会消失,使用`:redraw!`重绘屏幕也可以修复.

具体原因还不详,估计跟本插件关系也不大.
