### ISSUE TITLE
用Ctrl-C退出到普通模式发现并没有切换到英文，请问如何解决？

### ISSUE THREAD

**Issue by scottxing** [CodeFalling/fcitx-vim-osx#8]
Esc退到普通模式时会切换到英文，但是如果是用Ctrl-C退出到普通模式发现并没有切换到英文，请问如何解决？谢谢

**Comment by yzlnew** [comment]
看了下里面用到了 `InsertLeave` 不支持 `CTRL-C` 退出插入模式，请用 `CTRL-[`。

**Comment by bumaociyuan** [comment]
```
inoremap <c-c> <Esc> 
```

**Comment by yzlnew** [comment]
> ```
> inoremap <c-c> <Esc> 
> ```

不要 map `<esc>`
